### PR TITLE
Add SetUserAgent support.

### PR DESCRIPTION
**Pull request by ziyan**

### CODE REVIEW

**Comment by rdiankov** [comment]
thanks~

**Comment by cielavenir** [comment]
@ziyan for https://github.com/mujin/controllerclientcpp/pull/117, it was a signature CHANGE for EXISTING method so I needed to fix the python test, but does SetUserAgent require python bindings? I don't think so. /cc @lazydroid

**Comment by cielavenir** [comment]
@ziyan I will reply your yesterday's inquiry about controllerclientcpppy only after your answer this question.

**Comment by ziyan** [comment]
> @ziyan for #117, it was a signature CHANGE for EXISTING method so I needed to fix the python test, but does SetUserAgent require python bindings? I don't think so. /cc @lazydroid

I am not sure if I understand what you are trying to ask here. Do you mean that we do not need python bindings for methods added in controllerclientcpp? Do you mean it is automatically added?

**Comment by cielavenir** [comment]
> Do you mean it is automatically added?

No but we don't need bindings for function not in use

**Pull request merged**
