### PR TITLE
Fixed DeleteFileOnController webstack2

### PR DESCRIPTION
**Pull request by cielavenir**
CallPost uses "content-type:application/json" and putting raw parameter in data is not ok. need to use query string.

### CODE REVIEW

**Comment by ziyan** [comment]
@cielavenir 

1. Do you need to url encode the filename?
2. Please test against webstack2

**Comment by cielavenir** [comment]
I have run mujindeletefile sample against webstack2 environment, but yes, I have not tested url encode.

If I need it, how should I do?

**Comment by ziyan** [comment]
`EscapeString`

**Comment by cielavenir** [comment]
@ziyan I found that _PrepareDestinationURI_UTF8 calls EscapeString internally, so the URL is encoded.

On the other hand, I found that UploadFile must not encode the filename.Why webstack1 accepted encoded filename? Because webstack1 decodes filename field, which is wrong.

This MR itself is OK.

We need to:

- Make _PrepareDestinationURI_UTF8's URL encoding optional and disable encoding on UploadFile
- Make webstack fileupload not "unquoting" filename

**Comment by cielavenir** [comment]
@ziyan clientpy `self.UploadFile(open('hello%26delete.txt'))` causes creating `hello&delete.txt` in webstack1.

**Comment by cielavenir** [comment]
> Make webstack1 fileupload not "unquoting" filename

sent MR series.

But they can be independent with this MR. So please merge this quickly.

**Pull request merged**
