### PR TITLE
Handle external ref

### PR DESCRIPTION
**Pull request by cielavenir**
I have read webstack code carefully and understood that currently reference_uri and externalref values (in instobject.py) are tied, but not sure if we will support object copy mode (reference_uri with externalref=0).

I suggest adding the externalref parameter to set this situation. Also I added externalref parameter getter.

\# if `reference_uri and externalref values are tied` is our spec, I can tell Kei that.

### CODE REVIEW

**Comment by cielavenir** [comment]
Sent about the relevant webstack code line in mattermost message

**Comment by ziyan** [comment]
externalref is ignored on server side

To copy instaobject you should pass reference_pk instead.

**Comment by cielavenir** [comment]
@kanbouchou FYI https://github.com/mujin/controllerclientcpp/commit/d8cb5f08d93289f99f79542fc4b167273963a579 might be removed according to the conclusion (from savebackup branch).

**Comment by cielavenir** [comment]
@rdiankov May I ask your comment? Should we have another overload using reference_pk?

**Comment by cielavenir** [comment]
I talked with Ziyan again and confirmed that externalref parameter will not be used **even in the future.**

@rdiankov I'm very sorry to have confused you.

**Pull request closed without merging**
