### PR TITLE
Use references to limit greedy casting to bool

### PR DESCRIPTION
**Pull request by rschlaikjer**
When saving c-style arrays of values, it seems like gcc prefers to default to the bool version of SaveJsonValue preferentially even when 'better' fits exist. Changing the prototype for the primitives to take references seems to restrict it enough that the correct type is matched instead.

### CODE REVIEW

**Comment by rdiankov** [comment]
Does this pass our auto tests?

**Comment by rschlaikjer** [comment]
It passed pipeline id 549956 when I ran it a while ago, Ziyan just started another one (id 550698)

**Comment by rdiankov** [comment]
Kk, if that succeeds. Feel free to  merge. And add the dependency to the affected repo

**Comment by rschlaikjer** [comment]
Pipeline 550859 finished with 1251/50/56/7, merged

**Pull request merged**
