### PR TITLE
properly implemented Accept-Encoding:gzip (and changed windows curl binary to haxx one with zlib support)

### PR DESCRIPTION
**Pull request by cielavenir**
Tested on Windows as well.

However, unfortunately it turned out our libcurl binary does not enable zlib. I needed to use https://curl.haxx.se/windows/ for testing.

### CODE REVIEW

**Comment by rdiankov** [comment]
@cielavenir please update the PATCH version in CMakeLists.txt thanks

**Comment by cielavenir** [comment]
Done. Sorry to be late.

The issue is that when we set `CURL_OPTION_SETTER(_curl, CURLOPT_ACCEPT_ENCODING, "gzip, deflate");` using libcurl without libz support, transparent decompression does not work and gzipped data will be returned, which cannot be parsed by controllerclientcpp.

I needed to replace whole libcurl msvc binary. I cleaned up openssl include as well, which is not read by controllerclientcpp build system.

**Comment by rdiankov** [comment]
necessary? (@ziyan )

**Comment by cielavenir** [comment]
@ziyan currently controllerclientcpp does not use zlib

**Comment by ziyan** [comment]
I guess `controllerclientcpp` doesn't request compressed response from the server currenlty. But is that a problem @cielavenir I am curious where this PR is needed

**Comment by cielavenir** [comment]
Let's move to #108

**Pull request closed without merging**
