### PR TITLE
Add support for querying sensors in connected body.

### PR DESCRIPTION
**Pull request by ziyan**

### CODE REVIEW

**Comment by kanunikov-denys** [comment]
@ziyan what if we have connected body inside of the connected body? why don't we make a recursive function to explore all connected bodies?

**Comment by rdiankov** [comment]
@ziyan please update version

**Comment by ziyan** [comment]
> @ziyan what if we have connected body inside of the connected body? why don't we make a recursive function to explore all connected bodies?

@kanunikov-denys That's not something we support in OpenRAVE.

**Comment by ziyan** [comment]
@rdiankov Version bumped.

**Comment by rdiankov** [comment]
thanks~

**Pull request merged**
