### PR TITLE
Refactor ExecuteGraphQuery, ExecuteGraphQueryRaw

### PR DESCRIPTION
**Pull request by felixvd**
I want to add a flag for sending via ZMQ here, so want to clean up this duplicated code.

Autotester: https://autotester.test.mujin.co.jp/?scheduleid=2&pipelineid=344581

### CODE REVIEW

**Comment by cielavenir** [comment]
@felixvd are there any test cases handling ExecuteGraphQuery?

**Comment by cielavenir** [comment]
@felixvd added test_GraphClientListBodies to test_planningsystem, testing now

**Comment by cielavenir** [comment]
@felixvd ok, could you run another pipeline?

**Comment by cielavenir** [comment]
ran for you

pipelineid=344688
Pipeline #512074

**Comment by cielavenir** [comment]
test_GraphClientListBodies passed on both py and cpp

**Review by cielavenir — APPROVED** [review]

**Comment by rdiankov** [comment]
thanks

**Pull request merged**
