### PR TITLE
Determine default values for members that would be indetermine

### PR DESCRIPTION
**Pull request by hemangandhi**
From discussion in https://github.com/mujin/controllerclientcpp/pull/139: we might as well just determine all the indeterminate values.

(Master-based version of https://github.com/mujin/controllerclientcpp/pull/153, unlike https://github.com/mujin/controllerclientcpp/pull/139 this does not include https://github.com/mujin/controllerclientcpp/pull/146)

### CODE REVIEW

**Review by cielavenir — APPROVED** [review]
so far it's working, thank you!

**Comment by cielavenir** [comment]
@rdiankov please check this, without this the initial value is undefined

**Comment by rdiankov** [comment]
woot~ let's see if not changing version gets us in trouble

**Comment by felixvd** [comment]
Not on here, we're only doing that on Gitlab :slightly_smiling_face:

**Pull request merged**
